/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ecnu.sei.hif.view;

import edu.ecnu.sei.hif.algorithm.ImportantClassifier;
import edu.ecnu.sei.hif.algorithm.SpamClassifier;
import edu.ecnu.sei.hif.control.Client;
import edu.ecnu.sei.hif.model.EmailLabel;
import edu.ecnu.sei.hif.model.FolderTreeNode;
import edu.ecnu.sei.hif.model.StoreTreeNode;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author 一夫
 */
public class MainViewer extends javax.swing.JFrame {

    /**
     * Creates new form MainViewer
     */
    public MainViewer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane6 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jSplitPane8 = new javax.swing.JSplitPane();
        jSplitPane11 = new javax.swing.JSplitPane();
        jSplitPane13 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jSplitPane14 = new javax.swing.JSplitPane();
        jSplitPane15 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSplitPane10 = new javax.swing.JSplitPane();
        jSplitPane12 = new javax.swing.JSplitPane();
        jSplitPane16 = new javax.swing.JSplitPane();
        jPanel7 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jSplitPane17 = new javax.swing.JSplitPane();
        jSplitPane18 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        Client.envinbox = new EmailNetworkViewer("D:\\workspace\\netbeans\\Project\\data\\EmailNetwork_INBOX.xml");
        jPanel3 = Client.envinbox.view();
        jSplitPane5 = new javax.swing.JSplitPane();
        Client.envsent = new EmailNetworkViewer("D:\\workspace\\netbeans\\Project\\data\\EmailNetwork_SENT.xml");
        jPanel4 = Client.envsent.view();
        jSplitPane6 = new javax.swing.JSplitPane();
        Client.envall = new EmailNetworkViewer("D:\\workspace\\netbeans\\Project\\data\\EmailNetwork_ALL.xml");
        jPanel5 = Client.envall.view();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iEmail");
        setResizable(false);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setEnabled(false);

        jSplitPane2.setDividerLocation(600);
        jSplitPane2.setToolTipText("");
        jSplitPane2.setEnabled(false);
        Client.fv = new FolderViewer(null);
        jSplitPane2.setLeftComponent(Client.fv);
        Client.mv = new MessageViewer();
        jSplitPane2.setRightComponent(Client.mv);
        jSplitPane1.setRightComponent(jSplitPane2);

        jTree1.setModel(initialTreeMode());
        jTree1.addTreeSelectionListener(new TreePress());
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTabbedPane6.addTab("邮箱", jSplitPane1);

        jSplitPane8.setDividerLocation(500);
        jSplitPane8.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane8.setEnabled(false);

        jSplitPane11.setDividerLocation(1000);
        jSplitPane11.setEnabled(false);

        jSplitPane13.setDividerLocation(500);
        jSplitPane13.setEnabled(false);

        String prePath = "D:\\workspace\\netbeans\\Project\\data\\";
        String[] spamPath = {"Junk", "Deleted Messages"};
        String[] hamPath = {"Debris", "Drafts", "INBOX", "QQ邮件订阅", "Software Engineering", "邮件归档"};
        File[] spamFile = new File[spamPath.length];
        File[] hamFile = new File[hamPath.length];
        for (int i = 0; i < spamPath.length; i++) {
            spamFile[i] = new File(prePath + spamPath[i]);
        }
        for (int i = 0; i < hamPath.length; i++) {
            hamFile[i] = new File(prePath + hamPath[i]);
        }
        Client.spamlabel = new LinkedList<>();
        Client.fvcspam1 = new FolderViewerC1(spamFile);
        jSplitPane13.setLeftComponent(Client.fvcspam1);
        Client.fvcspam2 = new FolderViewerC2(hamFile);
        jSplitPane13.setRightComponent(Client.fvcspam2);

        jSplitPane11.setLeftComponent(jSplitPane13);

        jButton4.setText("训练");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jSplitPane11.setRightComponent(jPanel1);

        jSplitPane8.setTopComponent(jSplitPane11);

        jSplitPane14.setDividerLocation(1000);
        jSplitPane14.setEnabled(false);

        jSplitPane15.setDividerLocation(500);
        jSplitPane15.setEnabled(false);

        jButton3.setText("预测");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jSplitPane15.setRightComponent(jPanel6);

        String[] postPath = {"Debris", "Drafts", "INBOX", "QQ邮件订阅", "Software Engineering", "邮件归档", "Junk", "Deleted Messages"};
        File[] allFile = new File[postPath.length];
        for (int i = 0; i < postPath.length; i++) {
            allFile[i] = new File(prePath + postPath[i]);
        }
        Client.spamtest = new LinkedList<>();
        Client.fvcspam3 = new FolderViewerC3(allFile);
        jSplitPane15.setLeftComponent(Client.fvcspam3);

        jSplitPane14.setLeftComponent(jSplitPane15);

        jScrollPane2.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jSplitPane14.setRightComponent(jScrollPane2);

        jSplitPane8.setRightComponent(jSplitPane14);

        jTabbedPane2.addTab("垃圾邮件过滤", jSplitPane8);

        jSplitPane10.setDividerLocation(500);
        jSplitPane10.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane10.setEnabled(false);

        jSplitPane12.setDividerLocation(1000);
        jSplitPane12.setEnabled(false);

        jSplitPane16.setDividerLocation(500);
        jSplitPane16.setEnabled(false);

        String[] inboxsent = {"INBOX", "Sent Messages"};
        File[] inboxsentFile = new File[inboxsent.length];
        for (int i = 0; i < inboxsent.length; i++) {
            inboxsentFile[i] = new File(prePath + inboxsent[i]);
        }
        Client.importantlabel = new LinkedList<>();
        Client.fvcimportant4 = new FolderViewerC4(inboxsentFile);
        Client.fvcimportant5 = new FolderViewerC5(inboxsentFile);
        jSplitPane16.setLeftComponent(Client.fvcimportant4);
        jSplitPane16.setRightComponent(Client.fvcimportant5);

        jSplitPane12.setLeftComponent(jSplitPane16);

        jButton5.setText("训练");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(914, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jSplitPane12.setRightComponent(jPanel7);

        jSplitPane10.setTopComponent(jSplitPane12);

        jSplitPane17.setDividerLocation(1000);
        jSplitPane17.setEnabled(false);

        jSplitPane18.setDividerLocation(500);
        jSplitPane18.setEnabled(false);

        jButton6.setText("预测");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(603, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jSplitPane18.setRightComponent(jPanel8);

        Client.importanttest = new LinkedList<>();
        Client.fvcimportant6 = new FolderViewerC6(allFile);
        jSplitPane18.setLeftComponent(Client.fvcimportant6);

        jSplitPane17.setLeftComponent(jSplitPane18);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane7.setViewportView(jTextArea2);

        jSplitPane17.setRightComponent(jScrollPane7);

        jSplitPane10.setRightComponent(jSplitPane17);

        jTabbedPane2.addTab("重要邮件推荐", jSplitPane10);

        jTabbedPane6.addTab("分类", jTabbedPane2);

        jSplitPane3.setDividerLocation(1100);

        jButton1.setText("邮件地址信息抽取");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("邮件签名信息抽取");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        jSplitPane3.setRightComponent(jPanel2);

        Client.fvi1 = new FolderViewerI1(new File("D:\\workspace\\netbeans\\Project\\data\\Contact.txt"));
        jSplitPane3.setLeftComponent(Client.fvi1);

        jTabbedPane6.addTab("通讯录", jSplitPane3);

        jSplitPane4.setDividerLocation(500);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jSplitPane4.setRightComponent(jPanel3);

        Client.fvn1 = new FolderViewerN1(new File("D:\\workspace\\netbeans\\Project\\data\\EmailNetwork_INBOX.txt"));
        jSplitPane4.setLeftComponent(Client.fvn1);

        jTabbedPane1.addTab("收件箱", jSplitPane4);

        jSplitPane5.setDividerLocation(500);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jSplitPane5.setRightComponent(jPanel4);

        Client.fvn2 = new FolderViewerN2(new File("D:\\workspace\\netbeans\\Project\\data\\EmailNetwork_SENT.txt"));
        jSplitPane5.setLeftComponent(Client.fvn2);

        jTabbedPane1.addTab("发件箱", jSplitPane5);

        jSplitPane6.setDividerLocation(500);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jSplitPane6.setRightComponent(jPanel5);

        Client.fvn3 = new FolderViewerN3(new File("D:\\workspace\\netbeans\\Project\\data\\EmailNetwork_ALL.txt"));
        jSplitPane6.setLeftComponent(Client.fvn3);

        jTabbedPane1.addTab("全部", jSplitPane6);

        jTabbedPane6.addTab("可视化", jTabbedPane1);

        jMenu1.setText("菜单");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("邮件获取");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("关于");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("退出");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "个人邮件智能挖掘及可视化\nIntelligent Mining and Visualization of Personal Email\n作者：黄一夫\n邮箱：ifhuang91@gmail.com", "关于", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        LoginViewer lv = new LoginViewer();
        lv.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        lv.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        List<String> hamlist = new ArrayList<>();
        List<String> spamlist = new ArrayList<>();
        for (EmailLabel el : Client.spamlabel) {
            if (el.getLabel().equals("1")) {
                spamlist.add(el.getPath());
            } else {
                hamlist.add(el.getPath());
            }
        }
        String[] ham = new String[hamlist.size()];
        int i = 0;
        for (String path : hamlist) {
            ham[i++] = path;
        }
        String[] spam = new String[spamlist.size()];
        i = 0;
        for (String path : spamlist) {
            spam[i++] = path;
        }
        Client.sc = new SpamClassifier(ham, spam);
        Client.sc.train();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] spamtestPath = new String[Client.spamtest.size()];
        int i = 0;
        for (String path : Client.spamtest) {
            spamtestPath[i++] = path;
        }
        Client.sc.predict(spamtestPath);
        StringBuilder sb = new StringBuilder();
        try {
            BufferedReader br = new BufferedReader(new FileReader("D:\\workspace\\netbeans\\Project\\data\\spamTestSetOutput.txt"));
            String line = br.readLine();
            while (line != null) {
                sb.append(line).append("\n");
                line = br.readLine();
            }
            br.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextArea1.setText(sb.toString());
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        List<String> importantlist = new ArrayList<>();
        List<String> unimportantlist = new ArrayList<>();
        for (EmailLabel el : Client.importantlabel) {
            if (el.getLabel().equals("1")) {
                importantlist.add(el.getPath());
            } else {
                unimportantlist.add(el.getPath());
            }
        }
        String[] important = new String[importantlist.size()];
        int i = 0;
        for (String path : importantlist) {
            important[i++] = path;
        }
        String[] unimportant = new String[unimportantlist.size()];
        i = 0;
        for (String path : unimportantlist) {
            unimportant[i++] = path;
        }
        Client.icf = new ImportantClassifier();
        Client.icf.train(important, unimportant);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String[] importanttestPath = new String[Client.importanttest.size()];
        int i = 0;
        for (String path : Client.importanttest) {
            importanttestPath[i++] = path;
        }
        Client.icf.predict(importanttestPath);
        StringBuilder sb = new StringBuilder();
        try {
            for (i = 0; i < importanttestPath.length; i++) {
                BufferedReader br = new BufferedReader(new FileReader("D:\\workspace\\netbeans\\Project\\data\\" + importanttestPath[i].substring(importanttestPath[i].lastIndexOf("\\"))));
                String line = br.readLine();
                while (line != null) {
                    sb.append(line).append("\n");
                    line = br.readLine();
                }
                br.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jTextArea2.setText(sb.toString());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Client.fvi1.setFolder(new File("D:\\workspace\\netbeans\\Project\\data\\Contact_Address.txt"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Client.fvi1.setFolder(new File("D:\\workspace\\netbeans\\Project\\data\\Contact_Signature.txt"));
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private DefaultTreeModel initialTreeMode() {
        StoreTreeNode storenode = new StoreTreeNode(new File("D:\\workspace\\netbeans\\Project\\data"));
        DefaultTreeModel treeModel = new DefaultTreeModel(storenode);
        return treeModel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane10;
    private javax.swing.JSplitPane jSplitPane11;
    private javax.swing.JSplitPane jSplitPane12;
    private javax.swing.JSplitPane jSplitPane13;
    private javax.swing.JSplitPane jSplitPane14;
    private javax.swing.JSplitPane jSplitPane15;
    private javax.swing.JSplitPane jSplitPane16;
    private javax.swing.JSplitPane jSplitPane17;
    private javax.swing.JSplitPane jSplitPane18;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JSplitPane jSplitPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}

class TreePress implements TreeSelectionListener {
    
    public void valueChanged(TreeSelectionEvent e) {
        TreePath path = e.getNewLeadSelectionPath();
        if (path != null) {
            Object o = path.getLastPathComponent();
            if (o instanceof FolderTreeNode) {
                FolderTreeNode node = (FolderTreeNode) o;
                File folder = node.getFolder();
                
                try {
                    if (folder.exists() && folder.list().length != 0) {
                        Client.fv.setFolder(folder);
                    }
                } catch (Exception me) {
                    me.printStackTrace();
                }
            }
        }
    }
}
